import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Lilo & Stitch Case",
    phoneModel: "iPhone 15 Pro",
    brand: "Apple",
    price: 10,
    category: "Disney",
    imageUrl: "/images/products/1.png",
    description: "Cute Stitch watercolor case for iPhone 15 Pro",
    stock: 10,
  },
  {
    id: "2",
    name: "Marble Swirl Case",
    phoneModel: "Galaxy S24 Ultra",
    brand: "Samsung",
    price: 12,
    category: "Marble",
    imageUrl: "/images/products/2.png",
    description: "Elegant white and gold marble pattern case",
    stock: 15,
  },
  {
    id: "3",
    name: "Naruto Shippuden Case",
    phoneModel: "Pixel 8 Pro",
    brand: "Google",
    price: 14,
    category: "Anime",
    imageUrl: "/images/products/3.png",
    description: "Durable case featuring Naruto artwork",
    stock: 20,
  },
  {
    id: "4",
    name: "Clear Shockproof Case",
    phoneModel: "Xiaomi 14",
    brand: "Xiaomi",
    price: 8,
    category: "Transparent",
    imageUrl: "/images/products/4.png",
    description: "Slim case with reinforced corners",
    stock: 0,
  },
  {
    id: "5",
    name: "Retro Sunset Case",
    phoneModel: "iPhone SE",
    brand: "Apple",
    price: 9,
    category: "Aesthetic",
    imageUrl: "/images/products/5.png",
    description: "Vibrant retro sunset gradient phone case",
    stock: 25,
  },
  {
    id: "6",
    name: "Minimalist Wave Case",
    phoneModel: "Galaxy A55",
    brand: "Samsung",
    price: 11,
    category: "Minimalist",
    imageUrl: "/images/products/6.png",
    description: "Soft-touch case with a subtle wave texture",
    stock: 30,
  },
  {
    id: "7",
    name: "Floral Bloom Case",
    phoneModel: "Moto Edge 40",
    brand: "Motorola",
    price: 10,
    category: "Floral",
    imageUrl: "/images/products/7.png",
    description: "Delicate floral print on a matte finish case",
    stock: 35,
  },
  {
    id: "8",
    name: "Cyber Grid Case",
    phoneModel: "Moto G15",
    brand: "Motorola",
    price: 15,
    category: "Tech",
    imageUrl: "/images/products/8.png",
    description: "Minimal black case with a subtle futuristic grid pattern.",
    stock: 40,
  },
];
